### ISSUE TITLE
Currently breaks in some (oh no) contexts!

### ISSUE THREAD

**Issue by boehs** [bbottema/gulp-js-text-inject#2]
If you try this file: https://git.sr.ht/~boehs/site/blob/master/src/_data/deets/flowerpower.txt

It breaks, inserting wack characters and in general just not being very cool

Crazy UTF-8 issues!! Horrible!! Scary!! Do not panic! I have a fix!

**Comment by boehs** [comment]
If anyone has the misfortune of this issue like me before the fix gets merged, try installing https://www.npmjs.com/package/@boehs/gulp-js-text-inject

**Comment by bbottema** [comment]
published in version 1.1.1
